name: spinningwheel
description: "A new Flutter project."
publish_to: 'none' 
version: 0.1.0

environment:
    sdk: ">=2.17.0 <3.0.0"  # Modification de la version minimale du SDK Flutter

dependencies:
  flutter:
    sdk: flutter

  wheel_spin: ^1.0.2


  firebase_core: ^2.30.0
  firebase_auth: ^4.3.0  # Ajout du package firebase_auth
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  user_repository:
    path: packages/user_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets : 
    - assets/images/
